### ISSUE TITLE
7" Screen with SKR 3 EZ Board

### ISSUE THREAD

**Issue by BahamutWolf** [FLYmaker/FLY-Screen#10]
Hello, I have the following question: is the FLY display also compatible with the SRK 3 EZ from Bigtreetech? Can I use the connection diagram from the SKR 2 board for this or are the connections different there? Attached is a picture of the connection diagram.

![H2f18cf71e74944fdb3f9daccf1bdfaf3Q_1](https://user-images.githubusercontent.com/121379812/229273490-0fc56004-2406-4789-acdf-5de0708d83ee.png)

Thanks for the help.

**Comment by jaysuk** [comment]
It'll work with any screen with marlin.

**Comment by BahamutWolf** [comment]
And I can do the wiring as with the SKR 2, which can be seen at the bottom of the picture?

**Comment by jaysuk** [comment]
To a serial/screen/tft connector

**Comment by BahamutWolf** [comment]
OK. Thank you very much
