### ISSUE TITLE
Touch screen Mellow FLY 4,3 + BIGTREETECH SKR V1.4 Turbo (need help!)

### ISSUE THREAD

**Issue by Sputnik-Mars** [FLYmaker/FLY-Screen#5]
Hello, dear team!

Most recently, I purchased a Mellow FLY 4.3 touchscreen from you on the recommendation of the owner of the "ChuchaTV" channel for my BIGTREETECH SKR V1.4 Turbo motherboard to replace the BIGTREETECH TFT35 V3.0 touchscreen. I connected to the 32-bit motherboard, the screen turned on, but my 3D printer does not respond to commands from the screen. Why did this happen? And what do you need to do for this? I really ask you to help! My contact address is: eugen_eak@mail.ru

I have Marlin. Data from Marlin attached below.
Configuration.h

#define CONFIGURATION_H_VERSION 020007
#define SERIAL_PORT -1
#define SERIAL_PORT_2 0
#define BAUDRATE 115200
//#define CR10_STOCKDISPLAY

![2021-01-21_19-44-05](https://user-images.githubusercontent.com/77786949/105359097-3d79ca00-5c21-11eb-9420-4538292b0388.png)
![2021-01-21_19-44-48](https://user-images.githubusercontent.com/77786949/105359102-3fdc2400-5c21-11eb-904e-51c9c3eb0abf.png)

**Comment by FLYmaker** [comment]
I seem to solve it for you elsewhere

**Comment by Sputnik-Mars** [comment]
Problem solved, thank you!

**Comment by edgaralex1** [comment]
can you describe how you solved the problem

**Comment by Sputnik-Mars** [comment]
Hello!  Yes, I can describe a successful solution to the problem.  I will prepare the entire description and send it as a whole archive.  Translation into English from Russian Google Translate.
Здравствуйте! Да, смогу описать успешное решение проблемы. Я подготовлю всё описание и пришлю целым архивом. Перевод на английский с русского Google Translate. 
--
Отправлено из "Honor 9X". понедельник, 31 мая 2021г., 10:58 +06:00 от edgaralex1  ***@***.*** :
